# Generated by Django 3.1.4 on 2021-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(choices=[('Banking & SMEs', 'Banking & SMEs'), ('Commercial & Industries', 'Commercial & Industries')], max_length=200, null=True),
        ),
    ]
