# Generated by Django 3.1.4 on 2021-01-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_client_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rep_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
