# Generated by Django 3.1.4 on 2021-01-02 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_client_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('region', models.CharField(max_length=4, null=True)),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('contact_num', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(choices=[('Scheduled for Audit', 'Scheduled for Audit'), ('Scheduled for Data-logging', 'Scheduled for Data-logging'), ('Scheduled for Audit & Data-logging', 'Scheduled for Audit & Data-logging'), ('Pending Schedule', 'Pending Schedule'), ('Audited', 'Audited'), ('Data-logged', 'Data-logged'), ('Audited & Data-logged', 'Audited & Data-logged')], max_length=100, null=True)),
                ('date_recv', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audits.client')),
            ],
        ),
    ]
