# Generated by Django 3.1.4 on 2021-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('rep_name', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('site', models.ManyToManyField(null=True, to='audits.Site')),
            ],
        ),
    ]
